#' @title Get ott ids for a set of identifiers from four common databases
#' @description Retrieve Open Tree of Life IDs for a set of identifiers from four common databases: eol, gbid, ncbi, and iucn.
#'  This is currently *experimental* and does not attempt to do formatting or processing of the JSON output past parsing it into a list.
#'  **Do not use for mission-critical functionality unless you really need to.**
#' @author Francis Windram
#'
#' @param eol a numeric ID or numeric vector of eol ids indicating the particular taxa to evaluate.
#' @param gbif a numeric ID or numeric vector of gbif ids indicating the particular taxa to evaluate.
#' @param ncbi a numeric ID or numeric vector of ncbi ids indicating the particular taxa to evaluate.
#' @param iucn a numeric ID or numeric vector of iucn ids indicating the particular taxa to evaluate.
#' @param rate maximum number of calls to the API per second.
#' @param basereq an [httr2 request][httr2::request()] object, as generated by [oz_basereq()]. If `NA`, uses the default request.
#'
#' @return A list of maps between the given ids and their OTT counterparts
#'
#'
#' @examples
#' \dontrun{
#' identifier2ott(eol = c(1228387, 7674), gbif = c(1651891), ncbi = c(389061), iucn = (7377))
#' }
#'
#' @export
#'

identifier2ott <- function(eol = NA, gbif = NA, ncbi = NA, iucn = NA, rate = 5, basereq = NA) {
  cli_alert_warning("identifier2ott is currently experimental and returns the parsed JSON output essentially raw.")

  if (all(is.na(basereq))) {
    basereq <- oz_basereq()
  }

  if (all(is.na(c(eol, gbif, ncbi, iucn)))) {
    cli_abort("No identifiers specified!")
  }

  # SHOULD BE req_url_path_append("API/getOTT"), see https://github.com/OneZoom/OZtree/issues/867
  req <- basereq %>%
    req_url_path_append("API/getOTT.json")

  if (!all(is.na(eol))) {
    req <- req %>% req_url_query("eol" = eol, .multi = "explode")
  }
  if (!all(is.na(gbif))) {
    req <- req %>% req_url_query("gbif" = gbif, .multi = "explode")
  }
  if (!all(is.na(ncbi))) {
    req <- req %>% req_url_query("ncbi" = ncbi, .multi = "explode")
  }
  if (!all(is.na(iucn))) {
    req <- req %>% req_url_query("iucn" = iucn, .multi = "explode")
  }
  resp <- req %>%
    req_throttle(rate) %>%
    req_perform()

  out <- resp %>% resp_body_json()

  return(out)
}
