#' @title Get get images for a set of ott IDs
#' @description Retrieve reusable, phylogenetically diverse and representative images for a set of Open Tree of Life IDs.
#' @author Francis Windram
#'
#' @param otts a numeric ID or numeric vector of ott ids indicating the particular taxa to evaluate.
#' @param type whether to return any representative images, only images that have been verified as correctly identified, or only public domain images. Defaults to `"any"`.
#' @param rate maximum number of calls to the API per second.
#' @param key your OneZoom API key (defaults to the public key of `0` if not specified).
#' @param basereq an [httr2 request][httr2::request()] object, as generated by [oz_basereq()]. If `NA`, uses the default request.
#'
#' @return A data frame of the output image locations, names, identifiers and their usage rights.
#'
#' @section Types:
#' The following types valid options for the `type` argument:
#' - `"any"` - *any images*
#' - `"verified"` - *images verified as correctly identified*
#' - `"pd"` - *images explicitly in the public domain*
#'
#' @examples
#' \dontrun{
#' node_images(247341)
#'
#' node_images(c(247341, 563159, 269666, 504327, 668392), rate=5)
#'
#' node_images(c(247341, 563159, 269666, 504327, 668392), type="pd")
#' }
#'
#' @export
#'

node_images <- function(otts, type = "any", rate = 5, key = NA, basereq = NA) {

  if (!(type %in% c("any", "verified", "pd"))) {
    cli_alert_warning("Type {.val {type}} not allowed. Choose one of the following:")
    cli::cli_ul(c("{.val any}", "{.val verified} {.emph (verified as correctly identified)}", "{.val pd} {.emph (public domain)}"))
    cli_alert_info("Defaulting to {.val {'any'}} this time.")
    type <- "any"
  }

  if (all(is.na(basereq))) {
    basereq <- oz_basereq()
  }

  if (is.na(key)) {
    key <- 0
    if (length(otts) > 5) {
      cli_alert_warning("Public API key only allows users to send 5 IDs per request!")
      cli_alert_info("Truncating {.arg otts} to 5: {.val {otts[1:5]}}")
      otts <- otts[1:5]
    }
  }

  resp <- basereq %>%
    req_url_path_append("API/node_images") %>%
    req_url_query(
      "otts" = otts,
      "key" = key,
      "type" = type,
      .multi = "comma"
    ) %>%
    req_throttle(rate) %>%
    req_perform()

  out <- resp %>% resp_body_json()

  # Get image column names
  imgnames <- names(out$headers)
  out$headers <- NULL
  # Get image data
  out_df <- suppressWarnings(rbindlist(out$images, fill = TRUE, use.names = FALSE))
  colnames(out_df) <- imgnames
  # rebind image otts
  ott <- data.frame(ott = names(out$images))
  out_df <- bind_cols(ott, out_df)

  return(out_df)

}
