#' @title Get identifiers from other databases for a set of ott IDs
#' @description Retrieve identifiers from other databases through onezoom for a set of Open Tree of Life IDs.
#' @author Francis Windram
#'
#' @param otts a numeric ID or numeric vector of ott ids indicating the particular taxa to evaluate.
#' @param remove_empty remove columns if all entries are `NA`.
#' @param rate maximum number of calls to the API per second.
#' @param key your OneZoom API key (defaults to the public key of `0` if not specified).
#' @param basereq an [httr2 request][httr2::request()] object, as generated by [oz_basereq()]. If `NA`, uses the default request.
#'
#' @return A data frame of the input otts alongside their ids in other databases
#'
#' @section Identifiers:
#' The following identifiers are potentially returned
#' - `ncbi`
#' - `ifung`
#' - `worms`
#' - `irmng`
#' - `gbif`
#' - `ipni`
#' - `eol`
#' - `wikidata`
#' - `iucn` (only for leaf node taxa)
#'
#' @examples
#' \dontrun{
#' ott2identifiers(247341)
#'
#' ott2identifiers(c(247341, 563159, 269666, 504327, 668392), rate=5)
#'
#' ott2identifiers(c(247341, 563159, 269666, 504327, 668392), remove_empty=TRUE)
#' }
#'
#' @export
#'

ott2identifiers <- function(otts, remove_empty = FALSE, rate = 5, key = NA, basereq = NA) {
  if (all(is.na(basereq))) {
    basereq <- oz_basereq()
  }

  if (is.na(key)) {
    key <- 0
    if (length(otts) > 5) {
      cli_alert_warning("Public API key only allows users to send 5 IDs per request!")
      cli_alert_info("Truncating {.arg otts} to 5: {.val {otts[1:5]}}")
      otts <- otts[1:5]
    }
  }
  resp <- basereq %>%
    req_url_path_append("API/otts2identifiers") %>%
    req_url_query(
      "otts" = otts,
      "key" = key,
      .multi = "comma"
    ) %>%
    req_throttle(rate) %>%
    req_perform()

  out <- resp %>% resp_body_json()
  idnames <- names(out$headers)
  out$headers <- NULL
  out_df <- suppressWarnings(rbindlist(out$ids, fill = TRUE, use.names = FALSE))
  colnames(out_df) <- idnames

  if (remove_empty) {
    out_df <- out_df %>% dplyr::select(dplyr::where(~ !all(is.na(.))))
  }
  return(out_df)
}
