#' @title Get common (vernacular) names for a set of ott IDs
#' @description Retrieve common (vernacular) names from onezoom for a set of Open Tree of Life IDs.
#' @author Francis Windram
#'
#' @param otts a numeric ID or numeric vector of ott ids indicating the particular taxa to evaluate.
#' @param lang a language code to specify which language to use.
#'  This can be a 2 or 3 letter code such as `"en"` or `"fr"`, or a more specific regional code such as `"en-gb"` (British English) or `"zh-hant"` (Chinese, in traditional script).
#'  Defaults to `"en"`
#' @param findall return all names for each OTT, in decreasing order of preference.
#' @param include_unpreferred if `findall=FALSE` and there is no name marked as *"preferred"* for this `lang`, allow for return of names marked as *"unpreferred"*.
#' @param nulls If no common name is present in the specified `lang`, request that the server returns `null` instead. Note this is not really necessary to set as this is handled client-side, as such it may be removed.
#' @param rate maximum number of calls to the API per second.
#' @param key your OneZoom API key (defaults to the public key of `0` if not specified).
#' @param basereq an [httr2 request][httr2::request()] object, as generated by [oz_basereq()]. If `NA`, uses the default request.
#'
#' @return A data frame of the input otts alongside their popularity and popularity rank.
#'
#' @section Column Names:
#' If `findall=TRUE` is set, the output of this function is arbitrarily wide (as each OTT id has an arbitrary number of common names).
#' In this case, the columns are numbered after the initial `common` column (which is the most preferred name) with names following the formula `common_x` where x is the rank of the name between 2 and the largest number of common names returned.
#' If not all OTTs have the same number of common names, the extra columns will be filled with `NA` for those ids.
#'
#' @examples
#' \dontrun{
#' ott2common(247341)
#'
#' ott2common(c(247341, 563159, 269666, 504327, 668392), rate=5)
#'
#' ott2common(c(247341, 563159, 269666, 504327, 668392), findall=TRUE)
#' }
#'
#' @export
#'

ott2common <- function(otts, lang = "en", findall = FALSE,
                       include_unpreferred = FALSE, nulls = FALSE, rate = 5,
                       key = NA, basereq = NA) {
  if (all(is.na(basereq))) {
    basereq <- oz_basereq()
  }

  if (is.na(key)) {
    key <- 0
    if (length(otts) > 5) {
      cli_alert_warning("Public API key only allows users to send 5 IDs per request!")
      cli_alert_info("Truncating {.arg otts} to 5: {.val {otts[1:5]}}")
      otts <- otts[1:5]
    }
  }

  # THE PROPER WAY TO DO IT, but doesn't currently work due to an API bug
  # See https://github.com/OneZoom/OZtree/issues/866
  # resp <- basereq %>%
  #   req_url_path_append("API/otts2vns") %>%
  #   req_url_query(
  #     "otts" = otts,
  #     "key" = key,
  #     "lang" = lang,
  #     "all" = findall,
  #     "include_unpreferred" = include_unpreferred,
  #     "nulls" = nulls,
  #     .multi = "comma"
  #     ) %>%
  #   req_throttle(rate) %>%
  #   req_perform()

  req <- basereq %>%
    req_url_path_append("API/otts2vns") %>%
    req_url_query(
      "otts" = otts,
      "key" = key,
      .multi = "comma"
    )
  # Include other queries if present
  if (findall) {
    req <- req %>% req_url_query("all" = findall)
  }
  if (include_unpreferred) {
    req <- req %>% req_url_query("include_unpreferred" = include_unpreferred)
  }
  if (nulls) {
    req <- req %>% req_url_query("nulls" = nulls)
  }

  # Perform the actual request
  resp <- req %>%
    req_throttle(rate) %>%
    req_perform()

  out <- resp %>% resp_body_json()

  out$lang <- NULL

  # Extract and left_join if findall is not set
  if (!findall) {
    suppressWarnings(out_df <- data.frame(ott = as.numeric(names(out)), unlist(out)))
    colnames(out_df) <- c("ott", "common")
  } else {
    # Extract all possible names and name cols appropriately
    out_df <- bind_cols(data.frame(ott = as.numeric(names(out))), rbindlist(out, fill = TRUE, use.names = FALSE))
    colnames(out_df) <- c("ott", "common", paste0("common_", seq(2, length(out_df) - 1)))
  }
  ott <- NA
  out_final <- left_join(data.frame(ott = otts), out_df, by = dplyr::join_by(ott))
  return(out_final)
}
