#' @title Get popularity for a set of ott IDs
#' @description Retrieve popularity indices from onezoom for a set of Open Tree of Life IDs. See [https://www.onezoom.org/popularity](https://www.onezoom.org/popularity) for full methodology.
#' @author Francis Windram
#'
#' @param otts a numeric ID or numeric vector of ott ids indicating the particular taxa to evaluate.
#' @param maxtaxa An integer giving the maximum number of taxa to return.
#'  By default this is equivalent to the number of OTTs passed in: if expand_taxa is `TRUE`, you may wish to set this to a higher value.
#'  There is an upper limit on the maximum number of taxa you can ask for, which is determined by your API key.
#' @param expand Include all species which are descendants of the given OTTs (i.e. higher level taxa are "expanded" into their constituent species, and the returned taxa are all at the species level).
#'  You can mix OTTs for species and higher taxa in a single call: only higher taxa will be expanded.
#'  If the parameter is `FALSE` or not given, do not expand taxa and simply return data on the OTTs that have been passed in (note that higher level taxa will not contain popularity_rank information, which is only valid for species).
#' @param spread_evenly Divide the maximum number of taxa to return (e.g. as given by the max parameter) so that each of the N taxa that are passed in are limited to the top (max÷N) most popular species.
#'  Results are then combined and re-sorted, meaning that the final list of taxa returned may well contain fewer species than max.
#'  This only really makes sense when `expand=TRUE`.
#' @param taxon_names Return a scientific (Latin) name for each returned taxon, if one is available. Names are usually (but not necessarily) the same as the scientific name listed on the Open Tree of Life.
#' @param include_raw Also return the raw (non-phylogenetically informed) score for each taxon.
#' @param sort If this is set to `rank` or `raw` then do not order species by phylogenetic popularity score then OTT id (as is the default), but instead use an alternative order.
#'  If `raw`, then use the raw (non-phylogenetic) score, which may be zero or absent for some taxa such as these with no wikipedia page (the raw score is also returned, in the same way as it is when setting `include_raw=TRUE`).
#'  If `rank`, then order by species rank (lowest first, with higher level taxa at start) then by plain popularity score (highest first), and finally by OTT id. Since only species (not higher taxa) have a rank, this necessarily puts all species first.
#' @param rate maximum number of calls to the API per second.
#' @param key your OneZoom API key (defaults to the public key of `0` if not specified).
#' @param basereq an [httr2 request][httr2::request()] object, as generated by [oz_basereq()]. If `NA`, uses the default request.
#'
#' @return A data frame of the input otts alongside their popularity and popularity rank.
#'
#' @examples
#' \dontrun{
#' popularity(247341)
#'
#' popularity(c(247341, 563159, 269666, 504327, 668392), rate=5)
#'
#' popularity(c(247341, 563159, 269666, 504327, 668392), expand=TRUE, spread_evenly=TRUE, rate=5)
#' }
#'
#' @export
#'

popularity <- function(
  otts, maxtaxa = NA, expand = FALSE,
  spread_evenly = FALSE, taxon_names = FALSE,
  include_raw = FALSE, sort = NA,
  rate = 5, key = NA, basereq = NA
) {
  if (all(is.na(basereq))) {
    basereq <- oz_basereq()
  }

  if (is.na(key)) {
    key <- 0
    if (length(otts) > 5) {
      cli_alert_warning("Public API key only allows users to send 5 IDs per request!")
      cli_alert_info("Truncating {.arg otts} to 5: {.val {otts[1:5]}}")
      otts <- otts[1:5]
    }
  }

  req <- basereq %>%
    req_url_path_append("popularity/list")

  if (!is.na(maxtaxa)) {
    req <- req %>% req_url_query("max" = maxtaxa)
  }

  if (!is.na(sort)) {
    # Check whether sort is an allowed variant and warn if not?
    req <- req %>% req_url_query("sort" = sort)
  }

  resp <- req %>% req_url_query(
    "otts" = otts,
    "key" = key,
    "expand_taxa" = as.numeric(expand),
    "spread_taxa_evenly" = as.numeric(spread_evenly),
    "names" = as.numeric(taxon_names),
    "include_raw" = as.numeric(include_raw),
    .multi = "comma"
  ) %>%
    req_throttle(rate) %>%
    req_perform()

  out <- resp %>% resp_body_json()

  if (out$n_taxa <= 0) {
    cli_abort("No records found for {.val {otts}}.")
  }

  suppressWarnings(out_df <- rbindlist(out$data))
  if (!include_raw) {
    colnames(out_df) <- names(out$header)
  } else {
    # Remove when #875 is fixed.
    if (!("raw_popularity" %in% names(out$header))) {
      cli_alert_warning("Patching headers (see OneZoom issue #875)")
      if (length(names(out$header)) == 3) {
        # Just add at end
        colnames(out_df) <- c(names(out$header), "raw_popularity")
      } else {
        # Insert raw_popularity at index 4
        names_vec <- c(names(out$header)[1:3], "raw_popularity", names(out$header)[4:length(names(out$header))])
        colnames(out_df) <- names_vec
      }
    } else {
      colnames(out_df) <- names(out$header)
    }
  }
  attr(out_df, "tot_spp") <- out$tot_spp
  attr(out_df, "n_taxa") <- out$n_taxa
  return(out_df)
}
